spring:
  application:
    name: employee-service

  datasource:
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: root123

eureka:
  client:
  servie-url:
    defaultZone: http://localhost:8761/eureka/